<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="./airlines.xsl"?>
<!DOCTYPE airlines [
    <!ELEMENT airlines (airline+)>
    <!ELEMENT airline (id, name, street, city, region, country,parks+,routes+)>
    <!ELEMENT id (#PCDATA)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT street (#PCDATA)>
    <!ELEMENT city (#PCDATA)>
    <!ELEMENT region (#PCDATA)>
    <!ELEMENT country (#PCDATA)>
    <!ELEMENT parks (park+)>
    <!ELEMENT park (id, routeType, manufacturer,year)>
    <!ELEMENT routeType (#PCDATA)>
    <!ELEMENT manufacturer (#PCDATA)>
    <!ELEMENT year (#PCDATA)>
    <!ELEMENT routes (route+)>
    <!ELEMENT route (vehicle,departure+,destination+)>
    <!ELEMENT vehicle (#PCDATA)>
    <!ELEMENT departure (airport,city,region?,country)>
    <!ELEMENT airport (#PCDATA)>
    <!ELEMENT destination (airport,city,region?,country)>
]>
<airlines>
    <airline>
        <id>88ef283c-b44f-43f7-81e7-2c3e1266e2fe</id>
        <name>Hickle and Sons</name>
        <street>506 8th Court</street>
        <city>Providence</city>
        <region>Rhode Island</region>
        <country>United States</country>
        <parks>
            <park>
                <id>d1e1a67f-5e62-4495-957f-3b7c38613928</id>
                <routeType>short-distance</routeType>
                <manufacturer>Mann Inc</manufacturer>
                <year>2018</year>
            </park>
            <park>
                <id>0e194364-fb2d-469c-8be1-e4a1a02ce7b2</id>
                <routeType>short-distance</routeType>
                <manufacturer>Moen LLC</manufacturer>
                <year>2015</year>
            </park>
            <park>
                <id>42650abf-eab0-44e0-8995-031545685a91</id>
                <routeType>local</routeType>
                <manufacturer>Sipes, Rohan and Jerde</manufacturer>
                <year>1987</year>
            </park>
        </parks>
        <routes>
            <route>
                <vehicle>cf462119-4c9f-4d21-ab9f-80f33605f378</vehicle>
                <departure>
                    <airport>Balistreri-Pagac</airport>
                    <city>Gostivar</city>
                    <country>Macedonia</country>
                </departure>
                <destination>
                    <airport>Treutel Inc</airport>
                    <city>Vandœuvre-lès-Nancy</city>
                    <region>Lorraine</region>
                    <country>France</country>
                </destination>
            </route>
            <route>
                <vehicle>2579d016-e051-474f-994f-9ecb96543ca9</vehicle>
                <departure>
                    <airport>Buckridge LLC</airport>
                    <city>Ta&#x27;erqi</city>
                    <country>China</country>
                </departure>
                <destination>
                    <airport>Heller Inc</airport>
                    <city>Jeziorany</city>
                    <country>Poland</country>
                </destination>
            </route>
        </routes>
    </airline>
    <airline>
        <id>e72ee5a9-3bb6-4b60-b083-73cf88ed38e0</id>
        <name>Marks-Schaefer</name>
        <street>453 Bayside Parkway</street>
        <city>Lumby</city>
        <region>British Columbia</region>
        <country>Canada</country>
        <parks>
            <park>
                <id>c330c3a5-4dab-4eba-8857-ce45ce824109</id>
                <routeType>local</routeType>
                <manufacturer>Walter LLC</manufacturer>
                <year>2006</year>
            </park>
            <park>
                <id>6ce3ac85-069c-4a53-a584-cd9eac454a6c</id>
                <routeType>long-distance</routeType>
                <manufacturer>Becker Group</manufacturer>
                <year>2003</year>
            </park>
            <park>
                <id>b43469a5-d188-47dd-8335-5105083131cc</id>
                <routeType>short-distance</routeType>
                <manufacturer>Willms-Thiel</manufacturer>
                <year>1990</year>
            </park>
        </parks>
        <routes>
            <route>
                <vehicle>ea970d79-3ae5-42f0-81e0-c262985f63db</vehicle>
                <departure>
                    <airport>Bayer-Mante</airport>
                    <city>Abelheira</city>
                    <region>Porto</region>
                    <country>Portugal</country>
                </departure>
                <destination>
                    <airport>Beer-Bayer</airport>
                    <city>Tak Bai</city>
                    <country>Thailand</country>
                </destination>
            </route>
            <route>
                <vehicle>28c746c4-7cd5-469e-8cf9-36fb04efa2d0</vehicle>
                <departure>
                    <airport>Lubowitz, Pagac and Christiansen</airport>
                    <city>Malunda</city>
                    <country>Indonesia</country>
                </departure>
                <destination>
                    <airport>Mohr-Bernhard</airport>
                    <city>Nambalan</city>
                    <country>Philippines</country>
                </destination>
            </route>
        </routes>
    </airline>
    <airline>
        <id>d3890c4a-9318-4f43-96e5-c1dab32d6197</id>
        <name>Olson Group</name>
        <street>61 Buena Vista Avenue</street>
        <city>Cincinnati</city>
        <region>Ohio</region>
        <country>United States</country>
        <parks>
            <park>
                <id>b9cbd5f7-d0c7-4210-b8a9-92ab6ef86e39</id>
                <routeType>long-distance</routeType>
                <manufacturer>Hahn, Rosenbaum and Renner</manufacturer>
                <year>2000</year>
            </park>
            <park>
                <id>6ac12781-b269-45d9-b3f7-ffd6f054b849</id>
                <routeType>local</routeType>
                <manufacturer>O&#x27;Reilly Inc</manufacturer>
                <year>2005</year>
            </park>
            <park>
                <id>c451a7d7-540a-42fb-b872-5026a49a6337</id>
                <routeType>short-distance</routeType>
                <manufacturer>Conn-Nolan</manufacturer>
                <year>2002</year>
            </park>
        </parks>
        <routes>
            <route>
                <vehicle>f9d6cfe6-8294-44cb-b182-bd8c54943bd5</vehicle>
                <departure>
                    <airport>Wilkinson-Nikolaus</airport>
                    <city>Yanmen</city>
                    <country>China</country>
                </departure>
                <destination>
                    <airport>Reichert, Roob and Balistreri</airport>
                    <city>Santa</city>
                    <country>Peru</country>
                </destination>
            </route>
            <route>
                <vehicle>a448d3ae-8734-49df-ab2a-170fffc4c610</vehicle>
                <departure>
                    <airport>Barrows-Schmeler</airport>
                    <city>Vänersborg</city>
                    <region>Västra Götaland</region>
                    <country>Sweden</country>
                </departure>
                <destination>
                    <airport>Jerde-Anderson</airport>
                    <city>Akure</city>
                    <country>Nigeria</country>
                </destination>
            </route>
        </routes>
    </airline>
    <airline>
        <id>a6739349-84ed-41ad-97cb-a35be66f55a1</id>
        <name>Leannon-Bins</name>
        <street>2263 Huxley Court</street>
        <city>El Paso</city>
        <region>Texas</region>
        <country>United States</country>
        <parks>
            <park>
                <id>af31030c-07e8-403c-a3fd-6817d82bae45</id>
                <routeType>local</routeType>
                <manufacturer>Shanahan-Hoppe</manufacturer>
                <year>2009</year>
            </park>
            <park>
                <id>7c80a342-558a-4438-84eb-32978446cbc7</id>
                <routeType>local</routeType>
                <manufacturer>Rath Inc</manufacturer>
                <year>1996</year>
            </park>
            <park>
                <id>7a407ce1-a99d-4766-bb60-97c5c2b13836</id>
                <routeType>long-distance</routeType>
                <manufacturer>Graham, Pacocha and Pollich</manufacturer>
                <year>1986</year>
            </park>
        </parks>
        <routes>
            <route>
                <vehicle>678b337e-4570-4c1f-bd05-be05fecd45d9</vehicle>
                <departure>
                    <airport>Krajcik and Sons</airport>
                    <city>Unión</city>
                    <country>Argentina</country>
                </departure>
                <destination>
                    <airport>Collins-Kris</airport>
                    <city>Višnjevac</city>
                    <country>Croatia</country>
                </destination>
            </route>
            <route>
                <vehicle>a66e8f1c-4d4c-45b0-8ce8-176c97d80c5e</vehicle>
                <departure>
                    <airport>McGlynn LLC</airport>
                    <city>Gaozhai</city>
                    <country>China</country>
                </departure>
                <destination>
                    <airport>Reilly-Ortiz</airport>
                    <city>Fermelã</city>
                    <region>Aveiro</region>
                    <country>Portugal</country>
                </destination>
            </route>
        </routes>
    </airline>
    <airline>
        <id>dbd64922-58e4-4a0f-8769-4c685ef131b4</id>
        <name>Toy-Balistreri</name>
        <street>99317 Lukken Court</street>
        <city>Los Angeles</city>
        <region>California</region>
        <country>United States</country>
        <parks>
            <park>
                <id>204e8e29-c432-4501-9bd1-81c20f06725f</id>
                <routeType>long-distance</routeType>
                <manufacturer>Jacobi, Willms and Predovic</manufacturer>
                <year>2018</year>
            </park>
            <park>
                <id>a78f1424-f95d-4af1-ac5e-45a10df18e4d</id>
                <routeType>long-distance</routeType>
                <manufacturer>Grady, Davis and Nitzsche</manufacturer>
                <year>2014</year>
            </park>
            <park>
                <id>61d7b949-58b9-4ae0-860d-c2e544d20914</id>
                <routeType>local</routeType>
                <manufacturer>Bayer LLC</manufacturer>
                <year>1991</year>
            </park>
        </parks>
        <routes>
            <route>
                <vehicle>b9aaf947-c234-4f21-961d-88d20b4a0079</vehicle>
                <departure>
                    <airport>Spinka-Rodriguez</airport>
                    <city>Fenhe</city>
                    <country>China</country>
                </departure>
                <destination>
                    <airport>Goldner, Harris and Stroman</airport>
                    <city>Dalheim</city>
                    <country>Luxembourg</country>
                </destination>
            </route>
            <route>
                <vehicle>98d1ca66-0591-4896-892e-d406a49c1fa8</vehicle>
                <departure>
                    <airport>Considine LLC</airport>
                    <city>Moss</city>
                    <region>Ostfold</region>
                    <country>Norway</country>
                </departure>
                <destination>
                    <airport>Dicki-Hermann</airport>
                    <city>Ōtsuki</city>
                    <country>Japan</country>
                </destination>
            </route>
        </routes>
    </airline>
    <airline>
        <id>06013463-e5af-4ea5-a64a-2f2eb95c8726</id>
        <name>Koss, Harvey and DuBuque</name>
        <street>24118 Bowman Park</street>
        <city>Glasgow</city>
        <region>Scotland</region>
        <country>United Kingdom</country>
        <parks>
            <park>
                <id>f8d32364-c5a9-4e2b-86f0-e0d0eac4189a</id>
                <routeType>long-distance</routeType>
                <manufacturer>Bashirian LLC</manufacturer>
                <year>1986</year>
            </park>
            <park>
                <id>4e6cf1ff-1f14-412b-bb61-e45a26c8c130</id>
                <routeType>long-distance</routeType>
                <manufacturer>Little-Feil</manufacturer>
                <year>2020</year>
            </park>
            <park>
                <id>7c568456-6908-4359-8040-d1dc9ac71145</id>
                <routeType>local</routeType>
                <manufacturer>Muller, Goldner and Crist</manufacturer>
                <year>1983</year>
            </park>
        </parks>
        <routes>
            <route>
                <vehicle>f3bc020b-53c4-4e6b-828b-8be3c5778bb2</vehicle>
                <departure>
                    <airport>Fadel Inc</airport>
                    <city>Casal da Anja</city>
                    <region>Leiria</region>
                    <country>Portugal</country>
                </departure>
                <destination>
                    <airport>Mueller-Johnston</airport>
                    <city>Mogok</city>
                    <country>Myanmar</country>
                </destination>
            </route>
            <route>
                <vehicle>50c79a57-3afb-47a2-869a-5419fa5dbb3d</vehicle>
                <departure>
                    <airport>Lind-Dibbert</airport>
                    <city>Baoluan</city>
                    <country>China</country>
                </departure>
                <destination>
                    <airport>Grant Inc</airport>
                    <city>Palhoça</city>
                    <country>Brazil</country>
                </destination>
            </route>
        </routes>
    </airline>
    <airline>
        <id>48e509a3-f2a2-494b-a11c-66de0cfe67f9</id>
        <name>Schaden-Konopelski</name>
        <street>0 Donald Lane</street>
        <city>Tulsa</city>
        <region>Oklahoma</region>
        <country>United States</country>
        <parks>
            <park>
                <id>65d818af-d2da-4475-8f1c-dee3f3364e9b</id>
                <routeType>local</routeType>
                <manufacturer>Bernier-Beer</manufacturer>
                <year>2001</year>
            </park>
            <park>
                <id>90c86de3-1f90-439a-a62a-06f2d80d3360</id>
                <routeType>short-distance</routeType>
                <manufacturer>Ortiz-Nicolas</manufacturer>
                <year>1986</year>
            </park>
            <park>
                <id>ffbb2e3f-1305-4737-8760-8582fd3b5d52</id>
                <routeType>long-distance</routeType>
                <manufacturer>Hoeger-Kling</manufacturer>
                <year>1983</year>
            </park>
        </parks>
        <routes>
            <route>
                <vehicle>856e3a7e-6701-4efa-a412-204aaa36d645</vehicle>
                <departure>
                    <airport>Rath, Rempel and Green</airport>
                    <city>Jiuquan</city>
                    <country>China</country>
                </departure>
                <destination>
                    <airport>Streich LLC</airport>
                    <city>Thai Charoen</city>
                    <country>Thailand</country>
                </destination>
            </route>
            <route>
                <vehicle>20227701-eb37-438e-a1db-bb94fbfa04d6</vehicle>
                <departure>
                    <airport>Cruickshank and Sons</airport>
                    <city>Xingbin</city>
                    <country>China</country>
                </departure>
                <destination>
                    <airport>Lebsack, Turner and Reilly</airport>
                    <city>Karagay</city>
                    <country>Russia</country>
                </destination>
            </route>
        </routes>
    </airline>
    <airline>
        <id>283fd4e1-ec3c-4445-9150-8ad5067a84bc</id>
        <name>Olson-MacGyver</name>
        <street>9412 Muir Court</street>
        <city>Miami</city>
        <region>Florida</region>
        <country>United States</country>
        <parks>
            <park>
                <id>3a0b3f62-d8ff-4e55-9524-c1149633ccaf</id>
                <routeType>local</routeType>
                <manufacturer>Waelchi Inc</manufacturer>
                <year>1987</year>
            </park>
            <park>
                <id>6bb84f8c-b31d-44a8-87c1-a55c69953529</id>
                <routeType>short-distance</routeType>
                <manufacturer>Aufderhar and Sons</manufacturer>
                <year>2013</year>
            </park>
            <park>
                <id>557e1e1b-08fe-447f-9bf6-5516f9081ccb</id>
                <routeType>short-distance</routeType>
                <manufacturer>Hand Inc</manufacturer>
                <year>1985</year>
            </park>
        </parks>
        <routes>
            <route>
                <vehicle>64540c86-309a-4f8c-8111-a14bb8771623</vehicle>
                <departure>
                    <airport>Stanton, Sanford and Wilderman</airport>
                    <city>Aguilares</city>
                    <country>Argentina</country>
                </departure>
                <destination>
                    <airport>Waters-Koelpin</airport>
                    <city>Wang Chan</city>
                    <country>Thailand</country>
                </destination>
            </route>
            <route>
                <vehicle>5317fe82-a0e7-431d-a243-a473b5a84cbf</vehicle>
                <departure>
                    <airport>Bogisich LLC</airport>
                    <city>Hongguang</city>
                    <country>China</country>
                </departure>
                <destination>
                    <airport>Koelpin and Sons</airport>
                    <city>Sumberkemuning</city>
                    <country>Indonesia</country>
                </destination>
            </route>
        </routes>
    </airline>
    <airline>
        <id>ac9ed5a9-ba8d-4415-b927-d3a66a529351</id>
        <name>Durgan-Armstrong</name>
        <street>31566 Darwin Center</street>
        <city>Milton</city>
        <region>Ontario</region>
        <country>Canada</country>
        <parks>
            <park>
                <id>6e7984be-44c2-46b9-b7cb-86bc0b57928e</id>
                <routeType>short-distance</routeType>
                <manufacturer>O&#x27;Conner, Kunde and Runte</manufacturer>
                <year>2015</year>
            </park>
            <park>
                <id>56644278-2597-4014-8852-ff708af78f5f</id>
                <routeType>short-distance</routeType>
                <manufacturer>Volkman and Sons</manufacturer>
                <year>1987</year>
            </park>
            <park>
                <id>672cd508-19eb-42c5-aa68-51fd78305b49</id>
                <routeType>long-distance</routeType>
                <manufacturer>Barton-Ondricka</manufacturer>
                <year>2003</year>
            </park>
        </parks>
        <routes>
            <route>
                <vehicle>767ec0b2-030b-479f-988b-2aea21ed0478</vehicle>
                <departure>
                    <airport>Hessel, Schmeler and Gislason</airport>
                    <city>Dalam</city>
                    <country>Indonesia</country>
                </departure>
                <destination>
                    <airport>Hilpert, Emmerich and Yost</airport>
                    <city>Porkhov</city>
                    <country>Russia</country>
                </destination>
            </route>
            <route>
                <vehicle>3cceb6b4-c30b-4884-b606-4e81efd0f407</vehicle>
                <departure>
                    <airport>Dooley-Schroeder</airport>
                    <city>Březová</city>
                    <country>Czech Republic</country>
                </departure>
                <destination>
                    <airport>Hartmann Group</airport>
                    <city>Abade de Vermoim</city>
                    <region>Braga</region>
                    <country>Portugal</country>
                </destination>
            </route>
        </routes>
    </airline>
    <airline>
        <id>8568afe4-36c0-46f0-a97a-2d26834e4729</id>
        <name>Lakin-Reynolds</name>
        <street>340 2nd Crossing</street>
        <city>Charleston</city>
        <region>West Virginia</region>
        <country>United States</country>
        <parks>
            <park>
                <id>beb2404e-8c3a-42ed-a902-e6fcfcaf20d3</id>
                <routeType>short-distance</routeType>
                <manufacturer>Turner Inc</manufacturer>
                <year>2019</year>
            </park>
            <park>
                <id>55b85e6f-472d-4e0a-a045-af862d963a88</id>
                <routeType>long-distance</routeType>
                <manufacturer>Monahan LLC</manufacturer>
                <year>2008</year>
            </park>
            <park>
                <id>2b54361a-0b9b-41a2-bc3b-f7ce1554d082</id>
                <routeType>local</routeType>
                <manufacturer>Weimann-Lockman</manufacturer>
                <year>2017</year>
            </park>
        </parks>
        <routes>
            <route>
                <vehicle>17a5793c-8541-4fce-8259-025cd9667a30</vehicle>
                <departure>
                    <airport>Harber, McKenzie and Prohaska</airport>
                    <city>Karang Tengah</city>
                    <country>Indonesia</country>
                </departure>
                <destination>
                    <airport>Weber Group</airport>
                    <city>Zhangdiyingzi</city>
                    <country>China</country>
                </destination>
            </route>
            <route>
                <vehicle>693a7e27-c56d-415a-981f-d04a6b4315e5</vehicle>
                <departure>
                    <airport>Russel and Sons</airport>
                    <city>Zhongzuiling</city>
                    <country>China</country>
                </departure>
                <destination>
                    <airport>Streich-Wiza</airport>
                    <city>Sucun</city>
                    <country>China</country>
                </destination>
            </route>
        </routes>
    </airline>
    <airline>
        <id>f41f108c-6dbb-4006-b074-76bcc951f1c9</id>
        <name>Greenfelder Group</name>
        <street>93931 Stoughton Place</street>
        <city>Charleston</city>
        <region>West Virginia</region>
        <country>United States</country>
        <parks>
            <park>
                <id>f3fb700c-4723-46b7-813b-09af1785eeb2</id>
                <routeType>local</routeType>
                <manufacturer>Kunze-Medhurst</manufacturer>
                <year>1993</year>
            </park>
            <park>
                <id>b6a9331d-08b5-46b0-a6e3-d25e320782ca</id>
                <routeType>short-distance</routeType>
                <manufacturer>Larson Inc</manufacturer>
                <year>1989</year>
            </park>
            <park>
                <id>918c3c1c-e76b-471c-8853-676ba796f9f3</id>
                <routeType>local</routeType>
                <manufacturer>Nader, Schuppe and Walsh</manufacturer>
                <year>2009</year>
            </park>
        </parks>
        <routes>
            <route>
                <vehicle>d4a19bbe-7f13-443e-9572-945981f5e0ea</vehicle>
                <departure>
                    <airport>Kuhn and Sons</airport>
                    <city>Yeshan</city>
                    <country>China</country>
                </departure>
                <destination>
                    <airport>Daugherty, Ratke and Sanford</airport>
                    <city>Miura</city>
                    <country>Japan</country>
                </destination>
            </route>
            <route>
                <vehicle>9319ae34-cf6d-4da0-9bf2-f481878d6d42</vehicle>
                <departure>
                    <airport>Thompson, Romaguera and Johnston</airport>
                    <city>Buenavista</city>
                    <country>Colombia</country>
                </departure>
                <destination>
                    <airport>Jones Group</airport>
                    <city>Hebei</city>
                    <country>China</country>
                </destination>
            </route>
        </routes>
    </airline>
    <airline>
        <id>12675df3-9deb-4232-a377-cb67366a814e</id>
        <name>Smith, Kris and Mohr</name>
        <street>93095 5th Park</street>
        <city>Memphis</city>
        <region>Tennessee</region>
        <country>United States</country>
        <parks>
            <park>
                <id>02144c49-1d0d-42a7-ada1-c05516696247</id>
                <routeType>short-distance</routeType>
                <manufacturer>Feil-Rowe</manufacturer>
                <year>2010</year>
            </park>
            <park>
                <id>fa7f75a6-524a-4719-9e16-53e501a0fb7c</id>
                <routeType>long-distance</routeType>
                <manufacturer>Romaguera-Bahringer</manufacturer>
                <year>2020</year>
            </park>
            <park>
                <id>551aacfc-02c2-4ea4-875a-91e5a6ad2cd9</id>
                <routeType>short-distance</routeType>
                <manufacturer>Murphy Inc</manufacturer>
                <year>2015</year>
            </park>
        </parks>
        <routes>
            <route>
                <vehicle>233aaad2-9129-4c2f-9723-833b57bc62a2</vehicle>
                <departure>
                    <airport>Bashirian, Pfeffer and Hettinger</airport>
                    <city>Bardo</city>
                    <country>Poland</country>
                </departure>
                <destination>
                    <airport>Dickinson-Pacocha</airport>
                    <city>Malanday</city>
                    <country>Philippines</country>
                </destination>
            </route>
            <route>
                <vehicle>d94b119c-cddb-4a8c-af76-8e25cca3e3b7</vehicle>
                <departure>
                    <airport>Abshire-Schowalter</airport>
                    <city>General Conesa</city>
                    <country>Argentina</country>
                </departure>
                <destination>
                    <airport>Ward, King and Koepp</airport>
                    <city>Bergen</city>
                    <region>Hordaland</region>
                    <country>Norway</country>
                </destination>
            </route>
        </routes>
    </airline>
    <airline>
        <id>af4ac783-28f3-4a5c-8650-a81bde9329d4</id>
        <name>Dickens Inc</name>
        <street>2 Gale Street</street>
        <city>Berthierville</city>
        <region>Québec</region>
        <country>Canada</country>
        <parks>
            <park>
                <id>d2a67551-66b1-4dfb-b706-a8796fbdac73</id>
                <routeType>short-distance</routeType>
                <manufacturer>Bashirian, Johnston and Botsford</manufacturer>
                <year>2015</year>
            </park>
            <park>
                <id>fdaee798-c526-4a44-b800-fe95f948e716</id>
                <routeType>short-distance</routeType>
                <manufacturer>Bernhard Group</manufacturer>
                <year>2019</year>
            </park>
            <park>
                <id>de5945a6-36f1-47e6-aa42-2a6e74ce6679</id>
                <routeType>local</routeType>
                <manufacturer>Green, Jenkins and Spencer</manufacturer>
                <year>2008</year>
            </park>
        </parks>
        <routes>
            <route>
                <vehicle>b1e48abd-9314-4e2a-8df8-a9e9e40e37b4</vehicle>
                <departure>
                    <airport>Hickle, Huels and Miller</airport>
                    <city>Pale</city>
                    <country>Bosnia and Herzegovina</country>
                </departure>
                <destination>
                    <airport>Bahringer and Sons</airport>
                    <city>Hufang</city>
                    <country>China</country>
                </destination>
            </route>
            <route>
                <vehicle>3302dc63-8e7f-4bb2-bd0c-79b6c198ccc4</vehicle>
                <departure>
                    <airport>Batz Inc</airport>
                    <city>Bantardawa</city>
                    <country>Indonesia</country>
                </departure>
                <destination>
                    <airport>Mann, Schumm and Stiedemann</airport>
                    <city>Los Pinos</city>
                    <region>Guanajuato</region>
                    <country>Mexico</country>
                </destination>
            </route>
        </routes>
    </airline>
    <airline>
        <id>b1a54397-c759-4b1e-824a-b64a0e5cc3fc</id>
        <name>Turner and Sons</name>
        <street>77 Menomonie Park</street>
        <city>Albuquerque</city>
        <region>New Mexico</region>
        <country>United States</country>
        <parks>
            <park>
                <id>7e27d7d7-8804-4ca6-9c65-71c3b45cfcb1</id>
                <routeType>local</routeType>
                <manufacturer>Rohan Group</manufacturer>
                <year>2020</year>
            </park>
            <park>
                <id>cf1b2df6-9de0-4c68-8b73-b9b0b2944e7b</id>
                <routeType>local</routeType>
                <manufacturer>Leuschke-Ortiz</manufacturer>
                <year>2002</year>
            </park>
            <park>
                <id>d01f5387-30ed-4894-8e66-fb269adf17f4</id>
                <routeType>local</routeType>
                <manufacturer>Mann and Sons</manufacturer>
                <year>1988</year>
            </park>
        </parks>
        <routes>